version: "3.8"

services:
    newrelic:
        container_name: todolist-newrelic
        image: newrelic/php-daemon
        networks:
            - main
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todolist
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
        networks:
            - main
    database_test:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todolist_test
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '5306:3306'
        networks:
            - main
    php:
        build:
            context: ./docker
        volumes:
          - .:/var/www/projet8-todolist
        depends_on:
          - database
        networks:
            - main
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/projet8-todolist
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
        networks:
            - main
networks:
    main:
