version: "3.8"

services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todolist
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '4306:3306'
    php:
        build:
            context: ./docker
        volumes:
            - .:/var/www/projet8-todolist
        depends_on:
            - database
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/projet8-todolist
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database